### PR TITLE
Remove react

### PR DESCRIPTION
**Pull request by malachaifrazier**
ReactJS removed app-wide and `npm` updated

### CODE REVIEW

**Comment by malachaifrazier** [comment]
@JDHDEV why was this reverted?

**Comment by malachaifrazier** [comment]
Whoever reverted this commit @getzober @JDHDEV

**Comment by getzober** [comment]
I reverted it because there was conflict with this request and pull request #2, i then pulled PR2 then PR3, so its all in the develop branch now. basically i accidentally did them out of order

**Comment by malachaifrazier** [comment]
Ahh

**Pull request merged**
